# Configuración simple del proyecto
exportar_parquet: true
exportar_csv: true
salida_parquet: "data/outputs/parquet"
salida_csv: "data/outputs/csv"
logs_dir: "logs"
incremental:
  orders: true
  order_lines: true
  payments: true